name: regression
channels:
  - anaconda
  - defaults
dependencies:
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - notebook=5.7.2
  - python-dateutil=2.7.5
  - pip=18.1
  - python=3.6.5
  - setuptools=40.6.3
  - zlib=1.2.11
  - scikit-learn=0.20
  - pip:
    - matplotlib==3.0.2
    - numpy==1.15.4
    - pandas==0.23.4
    - joblib==0.13.1
    - scipy==1.2.0
    - spacy==2.0.18
    - tensorflow==1.12.0

